//! Rows far wider than any program here, and statements, orderings and
//! aggregates over them, to hold one claim: **nothing in this module runs a
//! caller out of backwards branches** ([ADR 126](../docs/adr/126-a-check-pays-for-its-own-branches.md)).
//!
//! A Row of 200 columns with 40-character names is photon's tables (20 to 40
//! columns) times five. Before each walk over a Row's fields raised a quota
//! sized from the Row, most of these stopped with "evaluation exceeded 1000
//! backwards branches" at a line in `row.zig`, which reads as a fault in the
//! Row. The types are declared here, apart from the tests, so a test's own
//! quota does not pay for them, and the tests call nothing that raises one.
//!
//! The columns are numbered and cycle through six types. They are written out
//! rather than generated while compiling, because a Row has to declare
//! `nilo_table` and a generated struct has no declarations.

const std = @import("std");
const core = @import("nilo_core");
const dialect = @import("dialect.zig");
const ddl = @import("ddl.zig");
const migrate = @import("migrate.zig");
const ordering = @import("ordering.zig");
const rawcheck = @import("rawcheck.zig");
const row_mod = @import("row.zig");
const schema = @import("schema.zig");
const shape = @import("shape.zig");
const snapshot = @import("snapshot.zig");
const statement = @import("statement.zig");

const testing = std.testing;
const Pg = dialect.Postgres;
const Lite = dialect.SQLite;
const Str = core.Str;

/// 200 columns, 40-character names.
const Wide = struct {
    pub const nilo_table = .{ .name = "wide", .key = .id };
    id: i64,
    col_0001_a_long_descriptive_name_padding: Str,
    col_0002_a_long_descriptive_name_padding: ?i32,
    col_0003_a_long_descriptive_name_padding: bool,
    col_0004_a_long_descriptive_name_padding: f64,
    col_0005_a_long_descriptive_name_padding: ?Str,
    col_0006_a_long_descriptive_name_padding: i64,
    col_0007_a_long_descriptive_name_padding: Str,
    col_0008_a_long_descriptive_name_padding: ?i32,
    col_0009_a_long_descriptive_name_padding: bool,
    col_0010_a_long_descriptive_name_padding: f64,
    col_0011_a_long_descriptive_name_padding: ?Str,
    col_0012_a_long_descriptive_name_padding: i64,
    col_0013_a_long_descriptive_name_padding: Str,
    col_0014_a_long_descriptive_name_padding: ?i32,
    col_0015_a_long_descriptive_name_padding: bool,
    col_0016_a_long_descriptive_name_padding: f64,
    col_0017_a_long_descriptive_name_padding: ?Str,
    col_0018_a_long_descriptive_name_padding: i64,
    col_0019_a_long_descriptive_name_padding: Str,
    col_0020_a_long_descriptive_name_padding: ?i32,
    col_0021_a_long_descriptive_name_padding: bool,
    col_0022_a_long_descriptive_name_padding: f64,
    col_0023_a_long_descriptive_name_padding: ?Str,
    col_0024_a_long_descriptive_name_padding: i64,
    col_0025_a_long_descriptive_name_padding: Str,
    col_0026_a_long_descriptive_name_padding: ?i32,
    col_0027_a_long_descriptive_name_padding: bool,
    col_0028_a_long_descriptive_name_padding: f64,
    col_0029_a_long_descriptive_name_padding: ?Str,
    col_0030_a_long_descriptive_name_padding: i64,
    col_0031_a_long_descriptive_name_padding: Str,
    col_0032_a_long_descriptive_name_padding: ?i32,
    col_0033_a_long_descriptive_name_padding: bool,
    col_0034_a_long_descriptive_name_padding: f64,
    col_0035_a_long_descriptive_name_padding: ?Str,
    col_0036_a_long_descriptive_name_padding: i64,
    col_0037_a_long_descriptive_name_padding: Str,
    col_0038_a_long_descriptive_name_padding: ?i32,
    col_0039_a_long_descriptive_name_padding: bool,
    col_0040_a_long_descriptive_name_padding: f64,
    col_0041_a_long_descriptive_name_padding: ?Str,
    col_0042_a_long_descriptive_name_padding: i64,
    col_0043_a_long_descriptive_name_padding: Str,
    col_0044_a_long_descriptive_name_padding: ?i32,
    col_0045_a_long_descriptive_name_padding: bool,
    col_0046_a_long_descriptive_name_padding: f64,
    col_0047_a_long_descriptive_name_padding: ?Str,
    col_0048_a_long_descriptive_name_padding: i64,
    col_0049_a_long_descriptive_name_padding: Str,
    col_0050_a_long_descriptive_name_padding: ?i32,
    col_0051_a_long_descriptive_name_padding: bool,
    col_0052_a_long_descriptive_name_padding: f64,
    col_0053_a_long_descriptive_name_padding: ?Str,
    col_0054_a_long_descriptive_name_padding: i64,
    col_0055_a_long_descriptive_name_padding: Str,
    col_0056_a_long_descriptive_name_padding: ?i32,
    col_0057_a_long_descriptive_name_padding: bool,
    col_0058_a_long_descriptive_name_padding: f64,
    col_0059_a_long_descriptive_name_padding: ?Str,
    col_0060_a_long_descriptive_name_padding: i64,
    col_0061_a_long_descriptive_name_padding: Str,
    col_0062_a_long_descriptive_name_padding: ?i32,
    col_0063_a_long_descriptive_name_padding: bool,
    col_0064_a_long_descriptive_name_padding: f64,
    col_0065_a_long_descriptive_name_padding: ?Str,
    col_0066_a_long_descriptive_name_padding: i64,
    col_0067_a_long_descriptive_name_padding: Str,
    col_0068_a_long_descriptive_name_padding: ?i32,
    col_0069_a_long_descriptive_name_padding: bool,
    col_0070_a_long_descriptive_name_padding: f64,
    col_0071_a_long_descriptive_name_padding: ?Str,
    col_0072_a_long_descriptive_name_padding: i64,
    col_0073_a_long_descriptive_name_padding: Str,
    col_0074_a_long_descriptive_name_padding: ?i32,
    col_0075_a_long_descriptive_name_padding: bool,
    col_0076_a_long_descriptive_name_padding: f64,
    col_0077_a_long_descriptive_name_padding: ?Str,
    col_0078_a_long_descriptive_name_padding: i64,
    col_0079_a_long_descriptive_name_padding: Str,
    col_0080_a_long_descriptive_name_padding: ?i32,
    col_0081_a_long_descriptive_name_padding: bool,
    col_0082_a_long_descriptive_name_padding: f64,
    col_0083_a_long_descriptive_name_padding: ?Str,
    col_0084_a_long_descriptive_name_padding: i64,
    col_0085_a_long_descriptive_name_padding: Str,
    col_0086_a_long_descriptive_name_padding: ?i32,
    col_0087_a_long_descriptive_name_padding: bool,
    col_0088_a_long_descriptive_name_padding: f64,
    col_0089_a_long_descriptive_name_padding: ?Str,
    col_0090_a_long_descriptive_name_padding: i64,
    col_0091_a_long_descriptive_name_padding: Str,
    col_0092_a_long_descriptive_name_padding: ?i32,
    col_0093_a_long_descriptive_name_padding: bool,
    col_0094_a_long_descriptive_name_padding: f64,
    col_0095_a_long_descriptive_name_padding: ?Str,
    col_0096_a_long_descriptive_name_padding: i64,
    col_0097_a_long_descriptive_name_padding: Str,
    col_0098_a_long_descriptive_name_padding: ?i32,
    col_0099_a_long_descriptive_name_padding: bool,
    col_0100_a_long_descriptive_name_padding: f64,
    col_0101_a_long_descriptive_name_padding: ?Str,
    col_0102_a_long_descriptive_name_padding: i64,
    col_0103_a_long_descriptive_name_padding: Str,
    col_0104_a_long_descriptive_name_padding: ?i32,
    col_0105_a_long_descriptive_name_padding: bool,
    col_0106_a_long_descriptive_name_padding: f64,
    col_0107_a_long_descriptive_name_padding: ?Str,
    col_0108_a_long_descriptive_name_padding: i64,
    col_0109_a_long_descriptive_name_padding: Str,
    col_0110_a_long_descriptive_name_padding: ?i32,
    col_0111_a_long_descriptive_name_padding: bool,
    col_0112_a_long_descriptive_name_padding: f64,
    col_0113_a_long_descriptive_name_padding: ?Str,
    col_0114_a_long_descriptive_name_padding: i64,
    col_0115_a_long_descriptive_name_padding: Str,
    col_0116_a_long_descriptive_name_padding: ?i32,
    col_0117_a_long_descriptive_name_padding: bool,
    col_0118_a_long_descriptive_name_padding: f64,
    col_0119_a_long_descriptive_name_padding: ?Str,
    col_0120_a_long_descriptive_name_padding: i64,
    col_0121_a_long_descriptive_name_padding: Str,
    col_0122_a_long_descriptive_name_padding: ?i32,
    col_0123_a_long_descriptive_name_padding: bool,
    col_0124_a_long_descriptive_name_padding: f64,
    col_0125_a_long_descriptive_name_padding: ?Str,
    col_0126_a_long_descriptive_name_padding: i64,
    col_0127_a_long_descriptive_name_padding: Str,
    col_0128_a_long_descriptive_name_padding: ?i32,
    col_0129_a_long_descriptive_name_padding: bool,
    col_0130_a_long_descriptive_name_padding: f64,
    col_0131_a_long_descriptive_name_padding: ?Str,
    col_0132_a_long_descriptive_name_padding: i64,
    col_0133_a_long_descriptive_name_padding: Str,
    col_0134_a_long_descriptive_name_padding: ?i32,
    col_0135_a_long_descriptive_name_padding: bool,
    col_0136_a_long_descriptive_name_padding: f64,
    col_0137_a_long_descriptive_name_padding: ?Str,
    col_0138_a_long_descriptive_name_padding: i64,
    col_0139_a_long_descriptive_name_padding: Str,
    col_0140_a_long_descriptive_name_padding: ?i32,
    col_0141_a_long_descriptive_name_padding: bool,
    col_0142_a_long_descriptive_name_padding: f64,
    col_0143_a_long_descriptive_name_padding: ?Str,
    col_0144_a_long_descriptive_name_padding: i64,
    col_0145_a_long_descriptive_name_padding: Str,
    col_0146_a_long_descriptive_name_padding: ?i32,
    col_0147_a_long_descriptive_name_padding: bool,
    col_0148_a_long_descriptive_name_padding: f64,
    col_0149_a_long_descriptive_name_padding: ?Str,
    col_0150_a_long_descriptive_name_padding: i64,
    col_0151_a_long_descriptive_name_padding: Str,
    col_0152_a_long_descriptive_name_padding: ?i32,
    col_0153_a_long_descriptive_name_padding: bool,
    col_0154_a_long_descriptive_name_padding: f64,
    col_0155_a_long_descriptive_name_padding: ?Str,
    col_0156_a_long_descriptive_name_padding: i64,
    col_0157_a_long_descriptive_name_padding: Str,
    col_0158_a_long_descriptive_name_padding: ?i32,
    col_0159_a_long_descriptive_name_padding: bool,
    col_0160_a_long_descriptive_name_padding: f64,
    col_0161_a_long_descriptive_name_padding: ?Str,
    col_0162_a_long_descriptive_name_padding: i64,
    col_0163_a_long_descriptive_name_padding: Str,
    col_0164_a_long_descriptive_name_padding: ?i32,
    col_0165_a_long_descriptive_name_padding: bool,
    col_0166_a_long_descriptive_name_padding: f64,
    col_0167_a_long_descriptive_name_padding: ?Str,
    col_0168_a_long_descriptive_name_padding: i64,
    col_0169_a_long_descriptive_name_padding: Str,
    col_0170_a_long_descriptive_name_padding: ?i32,
    col_0171_a_long_descriptive_name_padding: bool,
    col_0172_a_long_descriptive_name_padding: f64,
    col_0173_a_long_descriptive_name_padding: ?Str,
    col_0174_a_long_descriptive_name_padding: i64,
    col_0175_a_long_descriptive_name_padding: Str,
    col_0176_a_long_descriptive_name_padding: ?i32,
    col_0177_a_long_descriptive_name_padding: bool,
    col_0178_a_long_descriptive_name_padding: f64,
    col_0179_a_long_descriptive_name_padding: ?Str,
    col_0180_a_long_descriptive_name_padding: i64,
    col_0181_a_long_descriptive_name_padding: Str,
    col_0182_a_long_descriptive_name_padding: ?i32,
    col_0183_a_long_descriptive_name_padding: bool,
    col_0184_a_long_descriptive_name_padding: f64,
    col_0185_a_long_descriptive_name_padding: ?Str,
    col_0186_a_long_descriptive_name_padding: i64,
    col_0187_a_long_descriptive_name_padding: Str,
    col_0188_a_long_descriptive_name_padding: ?i32,
    col_0189_a_long_descriptive_name_padding: bool,
    col_0190_a_long_descriptive_name_padding: f64,
    col_0191_a_long_descriptive_name_padding: ?Str,
    col_0192_a_long_descriptive_name_padding: i64,
    col_0193_a_long_descriptive_name_padding: Str,
    col_0194_a_long_descriptive_name_padding: ?i32,
    col_0195_a_long_descriptive_name_padding: bool,
    col_0196_a_long_descriptive_name_padding: f64,
    col_0197_a_long_descriptive_name_padding: ?Str,
    col_0198_a_long_descriptive_name_padding: i64,
    col_0199_a_long_descriptive_name_padding: Str,
};

/// The same table, read whole by a narrower Row.
const Narrow = struct {
    pub const nilo_table = Wide;
    id: i64,
    col_0001_a_long_descriptive_name_padding: Str,
    col_0002_a_long_descriptive_name_padding: ?i32,
    col_0003_a_long_descriptive_name_padding: bool,
    col_0004_a_long_descriptive_name_padding: f64,
    col_0005_a_long_descriptive_name_padding: ?Str,
    col_0006_a_long_descriptive_name_padding: i64,
    col_0007_a_long_descriptive_name_padding: Str,
    col_0008_a_long_descriptive_name_padding: ?i32,
    col_0009_a_long_descriptive_name_padding: bool,
    col_0010_a_long_descriptive_name_padding: f64,
    col_0011_a_long_descriptive_name_padding: ?Str,
    col_0012_a_long_descriptive_name_padding: i64,
    col_0013_a_long_descriptive_name_padding: Str,
    col_0014_a_long_descriptive_name_padding: ?i32,
    col_0015_a_long_descriptive_name_padding: bool,
    col_0016_a_long_descriptive_name_padding: f64,
    col_0017_a_long_descriptive_name_padding: ?Str,
    col_0018_a_long_descriptive_name_padding: i64,
    col_0019_a_long_descriptive_name_padding: Str,
    col_0020_a_long_descriptive_name_padding: ?i32,
    col_0021_a_long_descriptive_name_padding: bool,
    col_0022_a_long_descriptive_name_padding: f64,
    col_0023_a_long_descriptive_name_padding: ?Str,
    col_0024_a_long_descriptive_name_padding: i64,
    col_0025_a_long_descriptive_name_padding: Str,
    col_0026_a_long_descriptive_name_padding: ?i32,
    col_0027_a_long_descriptive_name_padding: bool,
    col_0028_a_long_descriptive_name_padding: f64,
    col_0029_a_long_descriptive_name_padding: ?Str,
    col_0030_a_long_descriptive_name_padding: i64,
    col_0031_a_long_descriptive_name_padding: Str,
    col_0032_a_long_descriptive_name_padding: ?i32,
    col_0033_a_long_descriptive_name_padding: bool,
    col_0034_a_long_descriptive_name_padding: f64,
    col_0035_a_long_descriptive_name_padding: ?Str,
    col_0036_a_long_descriptive_name_padding: i64,
    col_0037_a_long_descriptive_name_padding: Str,
    col_0038_a_long_descriptive_name_padding: ?i32,
    col_0039_a_long_descriptive_name_padding: bool,
    col_0040_a_long_descriptive_name_padding: f64,
    col_0041_a_long_descriptive_name_padding: ?Str,
    col_0042_a_long_descriptive_name_padding: i64,
    col_0043_a_long_descriptive_name_padding: Str,
    col_0044_a_long_descriptive_name_padding: ?i32,
    col_0045_a_long_descriptive_name_padding: bool,
    col_0046_a_long_descriptive_name_padding: f64,
    col_0047_a_long_descriptive_name_padding: ?Str,
    col_0048_a_long_descriptive_name_padding: i64,
    col_0049_a_long_descriptive_name_padding: Str,
    col_0050_a_long_descriptive_name_padding: ?i32,
    col_0051_a_long_descriptive_name_padding: bool,
    col_0052_a_long_descriptive_name_padding: f64,
    col_0053_a_long_descriptive_name_padding: ?Str,
    col_0054_a_long_descriptive_name_padding: i64,
    col_0055_a_long_descriptive_name_padding: Str,
    col_0056_a_long_descriptive_name_padding: ?i32,
    col_0057_a_long_descriptive_name_padding: bool,
    col_0058_a_long_descriptive_name_padding: f64,
    col_0059_a_long_descriptive_name_padding: ?Str,
    col_0060_a_long_descriptive_name_padding: i64,
    col_0061_a_long_descriptive_name_padding: Str,
    col_0062_a_long_descriptive_name_padding: ?i32,
    col_0063_a_long_descriptive_name_padding: bool,
    col_0064_a_long_descriptive_name_padding: f64,
    col_0065_a_long_descriptive_name_padding: ?Str,
    col_0066_a_long_descriptive_name_padding: i64,
    col_0067_a_long_descriptive_name_padding: Str,
    col_0068_a_long_descriptive_name_padding: ?i32,
    col_0069_a_long_descriptive_name_padding: bool,
    col_0070_a_long_descriptive_name_padding: f64,
    col_0071_a_long_descriptive_name_padding: ?Str,
    col_0072_a_long_descriptive_name_padding: i64,
    col_0073_a_long_descriptive_name_padding: Str,
    col_0074_a_long_descriptive_name_padding: ?i32,
    col_0075_a_long_descriptive_name_padding: bool,
    col_0076_a_long_descriptive_name_padding: f64,
    col_0077_a_long_descriptive_name_padding: ?Str,
    col_0078_a_long_descriptive_name_padding: i64,
    col_0079_a_long_descriptive_name_padding: Str,
    col_0080_a_long_descriptive_name_padding: ?i32,
    col_0081_a_long_descriptive_name_padding: bool,
    col_0082_a_long_descriptive_name_padding: f64,
    col_0083_a_long_descriptive_name_padding: ?Str,
    col_0084_a_long_descriptive_name_padding: i64,
    col_0085_a_long_descriptive_name_padding: Str,
    col_0086_a_long_descriptive_name_padding: ?i32,
    col_0087_a_long_descriptive_name_padding: bool,
    col_0088_a_long_descriptive_name_padding: f64,
    col_0089_a_long_descriptive_name_padding: ?Str,
    col_0090_a_long_descriptive_name_padding: i64,
    col_0091_a_long_descriptive_name_padding: Str,
    col_0092_a_long_descriptive_name_padding: ?i32,
    col_0093_a_long_descriptive_name_padding: bool,
    col_0094_a_long_descriptive_name_padding: f64,
    col_0095_a_long_descriptive_name_padding: ?Str,
    col_0096_a_long_descriptive_name_padding: i64,
    col_0097_a_long_descriptive_name_padding: Str,
    col_0098_a_long_descriptive_name_padding: ?i32,
    col_0099_a_long_descriptive_name_padding: bool,
    col_0100_a_long_descriptive_name_padding: f64,
    col_0101_a_long_descriptive_name_padding: ?Str,
    col_0102_a_long_descriptive_name_padding: i64,
    col_0103_a_long_descriptive_name_padding: Str,
    col_0104_a_long_descriptive_name_padding: ?i32,
    col_0105_a_long_descriptive_name_padding: bool,
    col_0106_a_long_descriptive_name_padding: f64,
    col_0107_a_long_descriptive_name_padding: ?Str,
    col_0108_a_long_descriptive_name_padding: i64,
    col_0109_a_long_descriptive_name_padding: Str,
    col_0110_a_long_descriptive_name_padding: ?i32,
    col_0111_a_long_descriptive_name_padding: bool,
    col_0112_a_long_descriptive_name_padding: f64,
    col_0113_a_long_descriptive_name_padding: ?Str,
    col_0114_a_long_descriptive_name_padding: i64,
    col_0115_a_long_descriptive_name_padding: Str,
    col_0116_a_long_descriptive_name_padding: ?i32,
    col_0117_a_long_descriptive_name_padding: bool,
    col_0118_a_long_descriptive_name_padding: f64,
    col_0119_a_long_descriptive_name_padding: ?Str,
    col_0120_a_long_descriptive_name_padding: i64,
    col_0121_a_long_descriptive_name_padding: Str,
    col_0122_a_long_descriptive_name_padding: ?i32,
    col_0123_a_long_descriptive_name_padding: bool,
    col_0124_a_long_descriptive_name_padding: f64,
    col_0125_a_long_descriptive_name_padding: ?Str,
    col_0126_a_long_descriptive_name_padding: i64,
    col_0127_a_long_descriptive_name_padding: Str,
    col_0128_a_long_descriptive_name_padding: ?i32,
    col_0129_a_long_descriptive_name_padding: bool,
    col_0130_a_long_descriptive_name_padding: f64,
    col_0131_a_long_descriptive_name_padding: ?Str,
    col_0132_a_long_descriptive_name_padding: i64,
    col_0133_a_long_descriptive_name_padding: Str,
    col_0134_a_long_descriptive_name_padding: ?i32,
    col_0135_a_long_descriptive_name_padding: bool,
    col_0136_a_long_descriptive_name_padding: f64,
    col_0137_a_long_descriptive_name_padding: ?Str,
    col_0138_a_long_descriptive_name_padding: i64,
    col_0139_a_long_descriptive_name_padding: Str,
    col_0140_a_long_descriptive_name_padding: ?i32,
    col_0141_a_long_descriptive_name_padding: bool,
    col_0142_a_long_descriptive_name_padding: f64,
    col_0143_a_long_descriptive_name_padding: ?Str,
    col_0144_a_long_descriptive_name_padding: i64,
    col_0145_a_long_descriptive_name_padding: Str,
    col_0146_a_long_descriptive_name_padding: ?i32,
    col_0147_a_long_descriptive_name_padding: bool,
    col_0148_a_long_descriptive_name_padding: f64,
    col_0149_a_long_descriptive_name_padding: ?Str,
    col_0150_a_long_descriptive_name_padding: i64,
    col_0151_a_long_descriptive_name_padding: Str,
    col_0152_a_long_descriptive_name_padding: ?i32,
    col_0153_a_long_descriptive_name_padding: bool,
    col_0154_a_long_descriptive_name_padding: f64,
    col_0155_a_long_descriptive_name_padding: ?Str,
    col_0156_a_long_descriptive_name_padding: i64,
    col_0157_a_long_descriptive_name_padding: Str,
    col_0158_a_long_descriptive_name_padding: ?i32,
    col_0159_a_long_descriptive_name_padding: bool,
    col_0160_a_long_descriptive_name_padding: f64,
    col_0161_a_long_descriptive_name_padding: ?Str,
    col_0162_a_long_descriptive_name_padding: i64,
    col_0163_a_long_descriptive_name_padding: Str,
    col_0164_a_long_descriptive_name_padding: ?i32,
    col_0165_a_long_descriptive_name_padding: bool,
    col_0166_a_long_descriptive_name_padding: f64,
    col_0167_a_long_descriptive_name_padding: ?Str,
    col_0168_a_long_descriptive_name_padding: i64,
    col_0169_a_long_descriptive_name_padding: Str,
    col_0170_a_long_descriptive_name_padding: ?i32,
    col_0171_a_long_descriptive_name_padding: bool,
    col_0172_a_long_descriptive_name_padding: f64,
    col_0173_a_long_descriptive_name_padding: ?Str,
    col_0174_a_long_descriptive_name_padding: i64,
    col_0175_a_long_descriptive_name_padding: Str,
    col_0176_a_long_descriptive_name_padding: ?i32,
    col_0177_a_long_descriptive_name_padding: bool,
    col_0178_a_long_descriptive_name_padding: f64,
    col_0179_a_long_descriptive_name_padding: ?Str,
    col_0180_a_long_descriptive_name_padding: i64,
    col_0181_a_long_descriptive_name_padding: Str,
    col_0182_a_long_descriptive_name_padding: ?i32,
    col_0183_a_long_descriptive_name_padding: bool,
    col_0184_a_long_descriptive_name_padding: f64,
    col_0185_a_long_descriptive_name_padding: ?Str,
    col_0186_a_long_descriptive_name_padding: i64,
    col_0187_a_long_descriptive_name_padding: Str,
    col_0188_a_long_descriptive_name_padding: ?i32,
    col_0189_a_long_descriptive_name_padding: bool,
    col_0190_a_long_descriptive_name_padding: f64,
    col_0191_a_long_descriptive_name_padding: ?Str,
    col_0192_a_long_descriptive_name_padding: i64,
    col_0193_a_long_descriptive_name_padding: Str,
    col_0194_a_long_descriptive_name_padding: ?i32,
    col_0195_a_long_descriptive_name_padding: bool,
    col_0196_a_long_descriptive_name_padding: f64,
    col_0197_a_long_descriptive_name_padding: ?Str,
    col_0198_a_long_descriptive_name_padding: i64,
    col_0199_a_long_descriptive_name_padding: Str,
};

/// Every column but the key, as an insert writes them.
const all_values = .{
    .col_0001_a_long_descriptive_name_padding = "x",
    .col_0002_a_long_descriptive_name_padding = 1,
    .col_0003_a_long_descriptive_name_padding = true,
    .col_0004_a_long_descriptive_name_padding = 1.5,
    .col_0005_a_long_descriptive_name_padding = "x",
    .col_0006_a_long_descriptive_name_padding = 1,
    .col_0007_a_long_descriptive_name_padding = "x",
    .col_0008_a_long_descriptive_name_padding = 1,
    .col_0009_a_long_descriptive_name_padding = true,
    .col_0010_a_long_descriptive_name_padding = 1.5,
    .col_0011_a_long_descriptive_name_padding = "x",
    .col_0012_a_long_descriptive_name_padding = 1,
    .col_0013_a_long_descriptive_name_padding = "x",
    .col_0014_a_long_descriptive_name_padding = 1,
    .col_0015_a_long_descriptive_name_padding = true,
    .col_0016_a_long_descriptive_name_padding = 1.5,
    .col_0017_a_long_descriptive_name_padding = "x",
    .col_0018_a_long_descriptive_name_padding = 1,
    .col_0019_a_long_descriptive_name_padding = "x",
    .col_0020_a_long_descriptive_name_padding = 1,
    .col_0021_a_long_descriptive_name_padding = true,
    .col_0022_a_long_descriptive_name_padding = 1.5,
    .col_0023_a_long_descriptive_name_padding = "x",
    .col_0024_a_long_descriptive_name_padding = 1,
    .col_0025_a_long_descriptive_name_padding = "x",
    .col_0026_a_long_descriptive_name_padding = 1,
    .col_0027_a_long_descriptive_name_padding = true,
    .col_0028_a_long_descriptive_name_padding = 1.5,
    .col_0029_a_long_descriptive_name_padding = "x",
    .col_0030_a_long_descriptive_name_padding = 1,
    .col_0031_a_long_descriptive_name_padding = "x",
    .col_0032_a_long_descriptive_name_padding = 1,
    .col_0033_a_long_descriptive_name_padding = true,
    .col_0034_a_long_descriptive_name_padding = 1.5,
    .col_0035_a_long_descriptive_name_padding = "x",
    .col_0036_a_long_descriptive_name_padding = 1,
    .col_0037_a_long_descriptive_name_padding = "x",
    .col_0038_a_long_descriptive_name_padding = 1,
    .col_0039_a_long_descriptive_name_padding = true,
    .col_0040_a_long_descriptive_name_padding = 1.5,
    .col_0041_a_long_descriptive_name_padding = "x",
    .col_0042_a_long_descriptive_name_padding = 1,
    .col_0043_a_long_descriptive_name_padding = "x",
    .col_0044_a_long_descriptive_name_padding = 1,
    .col_0045_a_long_descriptive_name_padding = true,
    .col_0046_a_long_descriptive_name_padding = 1.5,
    .col_0047_a_long_descriptive_name_padding = "x",
    .col_0048_a_long_descriptive_name_padding = 1,
    .col_0049_a_long_descriptive_name_padding = "x",
    .col_0050_a_long_descriptive_name_padding = 1,
    .col_0051_a_long_descriptive_name_padding = true,
    .col_0052_a_long_descriptive_name_padding = 1.5,
    .col_0053_a_long_descriptive_name_padding = "x",
    .col_0054_a_long_descriptive_name_padding = 1,
    .col_0055_a_long_descriptive_name_padding = "x",
    .col_0056_a_long_descriptive_name_padding = 1,
    .col_0057_a_long_descriptive_name_padding = true,
    .col_0058_a_long_descriptive_name_padding = 1.5,
    .col_0059_a_long_descriptive_name_padding = "x",
    .col_0060_a_long_descriptive_name_padding = 1,
    .col_0061_a_long_descriptive_name_padding = "x",
    .col_0062_a_long_descriptive_name_padding = 1,
    .col_0063_a_long_descriptive_name_padding = true,
    .col_0064_a_long_descriptive_name_padding = 1.5,
    .col_0065_a_long_descriptive_name_padding = "x",
    .col_0066_a_long_descriptive_name_padding = 1,
    .col_0067_a_long_descriptive_name_padding = "x",
    .col_0068_a_long_descriptive_name_padding = 1,
    .col_0069_a_long_descriptive_name_padding = true,
    .col_0070_a_long_descriptive_name_padding = 1.5,
    .col_0071_a_long_descriptive_name_padding = "x",
    .col_0072_a_long_descriptive_name_padding = 1,
    .col_0073_a_long_descriptive_name_padding = "x",
    .col_0074_a_long_descriptive_name_padding = 1,
    .col_0075_a_long_descriptive_name_padding = true,
    .col_0076_a_long_descriptive_name_padding = 1.5,
    .col_0077_a_long_descriptive_name_padding = "x",
    .col_0078_a_long_descriptive_name_padding = 1,
    .col_0079_a_long_descriptive_name_padding = "x",
    .col_0080_a_long_descriptive_name_padding = 1,
    .col_0081_a_long_descriptive_name_padding = true,
    .col_0082_a_long_descriptive_name_padding = 1.5,
    .col_0083_a_long_descriptive_name_padding = "x",
    .col_0084_a_long_descriptive_name_padding = 1,
    .col_0085_a_long_descriptive_name_padding = "x",
    .col_0086_a_long_descriptive_name_padding = 1,
    .col_0087_a_long_descriptive_name_padding = true,
    .col_0088_a_long_descriptive_name_padding = 1.5,
    .col_0089_a_long_descriptive_name_padding = "x",
    .col_0090_a_long_descriptive_name_padding = 1,
    .col_0091_a_long_descriptive_name_padding = "x",
    .col_0092_a_long_descriptive_name_padding = 1,
    .col_0093_a_long_descriptive_name_padding = true,
    .col_0094_a_long_descriptive_name_padding = 1.5,
    .col_0095_a_long_descriptive_name_padding = "x",
    .col_0096_a_long_descriptive_name_padding = 1,
    .col_0097_a_long_descriptive_name_padding = "x",
    .col_0098_a_long_descriptive_name_padding = 1,
    .col_0099_a_long_descriptive_name_padding = true,
    .col_0100_a_long_descriptive_name_padding = 1.5,
    .col_0101_a_long_descriptive_name_padding = "x",
    .col_0102_a_long_descriptive_name_padding = 1,
    .col_0103_a_long_descriptive_name_padding = "x",
    .col_0104_a_long_descriptive_name_padding = 1,
    .col_0105_a_long_descriptive_name_padding = true,
    .col_0106_a_long_descriptive_name_padding = 1.5,
    .col_0107_a_long_descriptive_name_padding = "x",
    .col_0108_a_long_descriptive_name_padding = 1,
    .col_0109_a_long_descriptive_name_padding = "x",
    .col_0110_a_long_descriptive_name_padding = 1,
    .col_0111_a_long_descriptive_name_padding = true,
    .col_0112_a_long_descriptive_name_padding = 1.5,
    .col_0113_a_long_descriptive_name_padding = "x",
    .col_0114_a_long_descriptive_name_padding = 1,
    .col_0115_a_long_descriptive_name_padding = "x",
    .col_0116_a_long_descriptive_name_padding = 1,
    .col_0117_a_long_descriptive_name_padding = true,
    .col_0118_a_long_descriptive_name_padding = 1.5,
    .col_0119_a_long_descriptive_name_padding = "x",
    .col_0120_a_long_descriptive_name_padding = 1,
    .col_0121_a_long_descriptive_name_padding = "x",
    .col_0122_a_long_descriptive_name_padding = 1,
    .col_0123_a_long_descriptive_name_padding = true,
    .col_0124_a_long_descriptive_name_padding = 1.5,
    .col_0125_a_long_descriptive_name_padding = "x",
    .col_0126_a_long_descriptive_name_padding = 1,
    .col_0127_a_long_descriptive_name_padding = "x",
    .col_0128_a_long_descriptive_name_padding = 1,
    .col_0129_a_long_descriptive_name_padding = true,
    .col_0130_a_long_descriptive_name_padding = 1.5,
    .col_0131_a_long_descriptive_name_padding = "x",
    .col_0132_a_long_descriptive_name_padding = 1,
    .col_0133_a_long_descriptive_name_padding = "x",
    .col_0134_a_long_descriptive_name_padding = 1,
    .col_0135_a_long_descriptive_name_padding = true,
    .col_0136_a_long_descriptive_name_padding = 1.5,
    .col_0137_a_long_descriptive_name_padding = "x",
    .col_0138_a_long_descriptive_name_padding = 1,
    .col_0139_a_long_descriptive_name_padding = "x",
    .col_0140_a_long_descriptive_name_padding = 1,
    .col_0141_a_long_descriptive_name_padding = true,
    .col_0142_a_long_descriptive_name_padding = 1.5,
    .col_0143_a_long_descriptive_name_padding = "x",
    .col_0144_a_long_descriptive_name_padding = 1,
    .col_0145_a_long_descriptive_name_padding = "x",
    .col_0146_a_long_descriptive_name_padding = 1,
    .col_0147_a_long_descriptive_name_padding = true,
    .col_0148_a_long_descriptive_name_padding = 1.5,
    .col_0149_a_long_descriptive_name_padding = "x",
    .col_0150_a_long_descriptive_name_padding = 1,
    .col_0151_a_long_descriptive_name_padding = "x",
    .col_0152_a_long_descriptive_name_padding = 1,
    .col_0153_a_long_descriptive_name_padding = true,
    .col_0154_a_long_descriptive_name_padding = 1.5,
    .col_0155_a_long_descriptive_name_padding = "x",
    .col_0156_a_long_descriptive_name_padding = 1,
    .col_0157_a_long_descriptive_name_padding = "x",
    .col_0158_a_long_descriptive_name_padding = 1,
    .col_0159_a_long_descriptive_name_padding = true,
    .col_0160_a_long_descriptive_name_padding = 1.5,
    .col_0161_a_long_descriptive_name_padding = "x",
    .col_0162_a_long_descriptive_name_padding = 1,
    .col_0163_a_long_descriptive_name_padding = "x",
    .col_0164_a_long_descriptive_name_padding = 1,
    .col_0165_a_long_descriptive_name_padding = true,
    .col_0166_a_long_descriptive_name_padding = 1.5,
    .col_0167_a_long_descriptive_name_padding = "x",
    .col_0168_a_long_descriptive_name_padding = 1,
    .col_0169_a_long_descriptive_name_padding = "x",
    .col_0170_a_long_descriptive_name_padding = 1,
    .col_0171_a_long_descriptive_name_padding = true,
    .col_0172_a_long_descriptive_name_padding = 1.5,
    .col_0173_a_long_descriptive_name_padding = "x",
    .col_0174_a_long_descriptive_name_padding = 1,
    .col_0175_a_long_descriptive_name_padding = "x",
    .col_0176_a_long_descriptive_name_padding = 1,
    .col_0177_a_long_descriptive_name_padding = true,
    .col_0178_a_long_descriptive_name_padding = 1.5,
    .col_0179_a_long_descriptive_name_padding = "x",
    .col_0180_a_long_descriptive_name_padding = 1,
    .col_0181_a_long_descriptive_name_padding = "x",
    .col_0182_a_long_descriptive_name_padding = 1,
    .col_0183_a_long_descriptive_name_padding = true,
    .col_0184_a_long_descriptive_name_padding = 1.5,
    .col_0185_a_long_descriptive_name_padding = "x",
    .col_0186_a_long_descriptive_name_padding = 1,
    .col_0187_a_long_descriptive_name_padding = "x",
    .col_0188_a_long_descriptive_name_padding = 1,
    .col_0189_a_long_descriptive_name_padding = true,
    .col_0190_a_long_descriptive_name_padding = 1.5,
    .col_0191_a_long_descriptive_name_padding = "x",
    .col_0192_a_long_descriptive_name_padding = 1,
    .col_0193_a_long_descriptive_name_padding = "x",
    .col_0194_a_long_descriptive_name_padding = 1,
    .col_0195_a_long_descriptive_name_padding = true,
    .col_0196_a_long_descriptive_name_padding = 1.5,
    .col_0197_a_long_descriptive_name_padding = "x",
    .col_0198_a_long_descriptive_name_padding = 1,
    .col_0199_a_long_descriptive_name_padding = "x",
};

/// 24 aggregates, each narrowed by its own `.where`.
const Totals = struct {
    pub const nilo_table = Narrow;
    pub const nilo_aggregate = .{
        .agg_0000_a_long_aggregate_name_padding = .{ .sum = .col_0006_a_long_descriptive_name_padding, .where = .{ .col_0012_a_long_descriptive_name_padding = 1 } },
        .agg_0001_a_long_aggregate_name_padding = .{ .sum = .col_0012_a_long_descriptive_name_padding, .where = .{ .col_0018_a_long_descriptive_name_padding = 1 } },
        .agg_0002_a_long_aggregate_name_padding = .{ .sum = .col_0018_a_long_descriptive_name_padding, .where = .{ .col_0024_a_long_descriptive_name_padding = 1 } },
        .agg_0003_a_long_aggregate_name_padding = .{ .sum = .col_0024_a_long_descriptive_name_padding, .where = .{ .col_0030_a_long_descriptive_name_padding = 1 } },
        .agg_0004_a_long_aggregate_name_padding = .{ .sum = .col_0030_a_long_descriptive_name_padding, .where = .{ .col_0036_a_long_descriptive_name_padding = 1 } },
        .agg_0005_a_long_aggregate_name_padding = .{ .sum = .col_0036_a_long_descriptive_name_padding, .where = .{ .col_0042_a_long_descriptive_name_padding = 1 } },
        .agg_0006_a_long_aggregate_name_padding = .{ .sum = .col_0042_a_long_descriptive_name_padding, .where = .{ .col_0048_a_long_descriptive_name_padding = 1 } },
        .agg_0007_a_long_aggregate_name_padding = .{ .sum = .col_0048_a_long_descriptive_name_padding, .where = .{ .col_0054_a_long_descriptive_name_padding = 1 } },
        .agg_0008_a_long_aggregate_name_padding = .{ .sum = .col_0054_a_long_descriptive_name_padding, .where = .{ .col_0060_a_long_descriptive_name_padding = 1 } },
        .agg_0009_a_long_aggregate_name_padding = .{ .sum = .col_0060_a_long_descriptive_name_padding, .where = .{ .col_0066_a_long_descriptive_name_padding = 1 } },
        .agg_0010_a_long_aggregate_name_padding = .{ .sum = .col_0066_a_long_descriptive_name_padding, .where = .{ .col_0072_a_long_descriptive_name_padding = 1 } },
        .agg_0011_a_long_aggregate_name_padding = .{ .sum = .col_0072_a_long_descriptive_name_padding, .where = .{ .col_0078_a_long_descriptive_name_padding = 1 } },
        .agg_0012_a_long_aggregate_name_padding = .{ .sum = .col_0078_a_long_descriptive_name_padding, .where = .{ .col_0084_a_long_descriptive_name_padding = 1 } },
        .agg_0013_a_long_aggregate_name_padding = .{ .sum = .col_0084_a_long_descriptive_name_padding, .where = .{ .col_0090_a_long_descriptive_name_padding = 1 } },
        .agg_0014_a_long_aggregate_name_padding = .{ .sum = .col_0090_a_long_descriptive_name_padding, .where = .{ .col_0096_a_long_descriptive_name_padding = 1 } },
        .agg_0015_a_long_aggregate_name_padding = .{ .sum = .col_0096_a_long_descriptive_name_padding, .where = .{ .col_0102_a_long_descriptive_name_padding = 1 } },
        .agg_0016_a_long_aggregate_name_padding = .{ .sum = .col_0102_a_long_descriptive_name_padding, .where = .{ .col_0108_a_long_descriptive_name_padding = 1 } },
        .agg_0017_a_long_aggregate_name_padding = .{ .sum = .col_0108_a_long_descriptive_name_padding, .where = .{ .col_0114_a_long_descriptive_name_padding = 1 } },
        .agg_0018_a_long_aggregate_name_padding = .{ .sum = .col_0114_a_long_descriptive_name_padding, .where = .{ .col_0120_a_long_descriptive_name_padding = 1 } },
        .agg_0019_a_long_aggregate_name_padding = .{ .sum = .col_0120_a_long_descriptive_name_padding, .where = .{ .col_0126_a_long_descriptive_name_padding = 1 } },
        .agg_0020_a_long_aggregate_name_padding = .{ .sum = .col_0126_a_long_descriptive_name_padding, .where = .{ .col_0132_a_long_descriptive_name_padding = 1 } },
        .agg_0021_a_long_aggregate_name_padding = .{ .sum = .col_0132_a_long_descriptive_name_padding, .where = .{ .col_0138_a_long_descriptive_name_padding = 1 } },
        .agg_0022_a_long_aggregate_name_padding = .{ .sum = .col_0138_a_long_descriptive_name_padding, .where = .{ .col_0144_a_long_descriptive_name_padding = 1 } },
        .agg_0023_a_long_aggregate_name_padding = .{ .sum = .col_0144_a_long_descriptive_name_padding, .where = .{ .col_0150_a_long_descriptive_name_padding = 1 } },
    };
    id: i64,
    agg_0000_a_long_aggregate_name_padding: ?i64,
    agg_0001_a_long_aggregate_name_padding: ?i64,
    agg_0002_a_long_aggregate_name_padding: ?i64,
    agg_0003_a_long_aggregate_name_padding: ?i64,
    agg_0004_a_long_aggregate_name_padding: ?i64,
    agg_0005_a_long_aggregate_name_padding: ?i64,
    agg_0006_a_long_aggregate_name_padding: ?i64,
    agg_0007_a_long_aggregate_name_padding: ?i64,
    agg_0008_a_long_aggregate_name_padding: ?i64,
    agg_0009_a_long_aggregate_name_padding: ?i64,
    agg_0010_a_long_aggregate_name_padding: ?i64,
    agg_0011_a_long_aggregate_name_padding: ?i64,
    agg_0012_a_long_aggregate_name_padding: ?i64,
    agg_0013_a_long_aggregate_name_padding: ?i64,
    agg_0014_a_long_aggregate_name_padding: ?i64,
    agg_0015_a_long_aggregate_name_padding: ?i64,
    agg_0016_a_long_aggregate_name_padding: ?i64,
    agg_0017_a_long_aggregate_name_padding: ?i64,
    agg_0018_a_long_aggregate_name_padding: ?i64,
    agg_0019_a_long_aggregate_name_padding: ?i64,
    agg_0020_a_long_aggregate_name_padding: ?i64,
    agg_0021_a_long_aggregate_name_padding: ?i64,
    agg_0022_a_long_aggregate_name_padding: ?i64,
    agg_0023_a_long_aggregate_name_padding: ?i64,
};

/// An enum of 600 values with 38-character names, which is more
/// than any program declares.
const Kind = blk: {
    @setEvalBranchQuota(10_000_000);
    var names: [600][:0]const u8 = undefined;
    var values: [600]u16 = undefined;
    for (&names, &values, 0..) |*name, *value, i| {
        name.* = std.fmt.comptimePrint("an_enum_value_with_a_longish_name_{d:0>4}", .{i});
        value.* = i;
    }
    break :blk @Enum(u16, .exhaustive, &names, &values);
};

const Labelled = struct {
    pub const nilo_table = .{ .name = "labelled", .key = .id };
    id: i64,
    kind: Kind,
    other: ?Kind,
};

/// Every column of `Wide`, spelled the way a person writing the statement would.
const wide_select = blk: {
    @setEvalBranchQuota(1_000_000);
    var out: []const u8 = "SELECT id";
    for (@typeInfo(Wide).@"struct".field_names[1..]) |f_name| out = out ++ ", " ++ f_name;
    break :blk out ++ " FROM wide WHERE id = $1";
};

const sort_keys = .{
    .col_0001_a_long_descriptive_name_padding = .col_0001_a_long_descriptive_name_padding,
    .col_0002_a_long_descriptive_name_padding = .col_0002_a_long_descriptive_name_padding,
    .col_0003_a_long_descriptive_name_padding = .col_0003_a_long_descriptive_name_padding,
    .col_0004_a_long_descriptive_name_padding = .col_0004_a_long_descriptive_name_padding,
    .col_0005_a_long_descriptive_name_padding = .col_0005_a_long_descriptive_name_padding,
    .col_0006_a_long_descriptive_name_padding = .col_0006_a_long_descriptive_name_padding,
    .col_0007_a_long_descriptive_name_padding = .col_0007_a_long_descriptive_name_padding,
    .col_0008_a_long_descriptive_name_padding = .col_0008_a_long_descriptive_name_padding,
    .col_0009_a_long_descriptive_name_padding = .col_0009_a_long_descriptive_name_padding,
    .col_0010_a_long_descriptive_name_padding = .col_0010_a_long_descriptive_name_padding,
    .col_0011_a_long_descriptive_name_padding = .col_0011_a_long_descriptive_name_padding,
    .col_0012_a_long_descriptive_name_padding = .col_0012_a_long_descriptive_name_padding,
    .col_0013_a_long_descriptive_name_padding = .col_0013_a_long_descriptive_name_padding,
    .col_0014_a_long_descriptive_name_padding = .col_0014_a_long_descriptive_name_padding,
    .col_0015_a_long_descriptive_name_padding = .col_0015_a_long_descriptive_name_padding,
    .col_0016_a_long_descriptive_name_padding = .col_0016_a_long_descriptive_name_padding,
    .col_0017_a_long_descriptive_name_padding = .col_0017_a_long_descriptive_name_padding,
    .col_0018_a_long_descriptive_name_padding = .col_0018_a_long_descriptive_name_padding,
    .col_0019_a_long_descriptive_name_padding = .col_0019_a_long_descriptive_name_padding,
    .col_0020_a_long_descriptive_name_padding = .col_0020_a_long_descriptive_name_padding,
    .col_0021_a_long_descriptive_name_padding = .col_0021_a_long_descriptive_name_padding,
    .col_0022_a_long_descriptive_name_padding = .col_0022_a_long_descriptive_name_padding,
    .col_0023_a_long_descriptive_name_padding = .col_0023_a_long_descriptive_name_padding,
    .col_0024_a_long_descriptive_name_padding = .col_0024_a_long_descriptive_name_padding,
    .col_0025_a_long_descriptive_name_padding = .col_0025_a_long_descriptive_name_padding,
    .col_0026_a_long_descriptive_name_padding = .col_0026_a_long_descriptive_name_padding,
    .col_0027_a_long_descriptive_name_padding = .col_0027_a_long_descriptive_name_padding,
    .col_0028_a_long_descriptive_name_padding = .col_0028_a_long_descriptive_name_padding,
    .col_0029_a_long_descriptive_name_padding = .col_0029_a_long_descriptive_name_padding,
    .col_0030_a_long_descriptive_name_padding = .col_0030_a_long_descriptive_name_padding,
    .col_0031_a_long_descriptive_name_padding = .col_0031_a_long_descriptive_name_padding,
    .col_0032_a_long_descriptive_name_padding = .col_0032_a_long_descriptive_name_padding,
    .col_0033_a_long_descriptive_name_padding = .col_0033_a_long_descriptive_name_padding,
    .col_0034_a_long_descriptive_name_padding = .col_0034_a_long_descriptive_name_padding,
    .col_0035_a_long_descriptive_name_padding = .col_0035_a_long_descriptive_name_padding,
    .col_0036_a_long_descriptive_name_padding = .col_0036_a_long_descriptive_name_padding,
    .col_0037_a_long_descriptive_name_padding = .col_0037_a_long_descriptive_name_padding,
    .col_0038_a_long_descriptive_name_padding = .col_0038_a_long_descriptive_name_padding,
    .col_0039_a_long_descriptive_name_padding = .col_0039_a_long_descriptive_name_padding,
    .col_0040_a_long_descriptive_name_padding = .col_0040_a_long_descriptive_name_padding,
    .col_0041_a_long_descriptive_name_padding = .col_0041_a_long_descriptive_name_padding,
    .col_0042_a_long_descriptive_name_padding = .col_0042_a_long_descriptive_name_padding,
    .col_0043_a_long_descriptive_name_padding = .col_0043_a_long_descriptive_name_padding,
    .col_0044_a_long_descriptive_name_padding = .col_0044_a_long_descriptive_name_padding,
    .col_0045_a_long_descriptive_name_padding = .col_0045_a_long_descriptive_name_padding,
    .col_0046_a_long_descriptive_name_padding = .col_0046_a_long_descriptive_name_padding,
    .col_0047_a_long_descriptive_name_padding = .col_0047_a_long_descriptive_name_padding,
    .col_0048_a_long_descriptive_name_padding = .col_0048_a_long_descriptive_name_padding,
    .col_0049_a_long_descriptive_name_padding = .col_0049_a_long_descriptive_name_padding,
    .col_0050_a_long_descriptive_name_padding = .col_0050_a_long_descriptive_name_padding,
    .col_0051_a_long_descriptive_name_padding = .col_0051_a_long_descriptive_name_padding,
    .col_0052_a_long_descriptive_name_padding = .col_0052_a_long_descriptive_name_padding,
    .col_0053_a_long_descriptive_name_padding = .col_0053_a_long_descriptive_name_padding,
    .col_0054_a_long_descriptive_name_padding = .col_0054_a_long_descriptive_name_padding,
    .col_0055_a_long_descriptive_name_padding = .col_0055_a_long_descriptive_name_padding,
    .col_0056_a_long_descriptive_name_padding = .col_0056_a_long_descriptive_name_padding,
    .col_0057_a_long_descriptive_name_padding = .col_0057_a_long_descriptive_name_padding,
    .col_0058_a_long_descriptive_name_padding = .col_0058_a_long_descriptive_name_padding,
    .col_0059_a_long_descriptive_name_padding = .col_0059_a_long_descriptive_name_padding,
    .col_0060_a_long_descriptive_name_padding = .col_0060_a_long_descriptive_name_padding,
    .col_0061_a_long_descriptive_name_padding = .col_0061_a_long_descriptive_name_padding,
    .col_0062_a_long_descriptive_name_padding = .col_0062_a_long_descriptive_name_padding,
    .col_0063_a_long_descriptive_name_padding = .col_0063_a_long_descriptive_name_padding,
    .col_0064_a_long_descriptive_name_padding = .col_0064_a_long_descriptive_name_padding,
    .col_0065_a_long_descriptive_name_padding = .col_0065_a_long_descriptive_name_padding,
    .col_0066_a_long_descriptive_name_padding = .col_0066_a_long_descriptive_name_padding,
    .col_0067_a_long_descriptive_name_padding = .col_0067_a_long_descriptive_name_padding,
    .col_0068_a_long_descriptive_name_padding = .col_0068_a_long_descriptive_name_padding,
    .col_0069_a_long_descriptive_name_padding = .col_0069_a_long_descriptive_name_padding,
    .col_0070_a_long_descriptive_name_padding = .col_0070_a_long_descriptive_name_padding,
    .col_0071_a_long_descriptive_name_padding = .col_0071_a_long_descriptive_name_padding,
    .col_0072_a_long_descriptive_name_padding = .col_0072_a_long_descriptive_name_padding,
    .col_0073_a_long_descriptive_name_padding = .col_0073_a_long_descriptive_name_padding,
    .col_0074_a_long_descriptive_name_padding = .col_0074_a_long_descriptive_name_padding,
    .col_0075_a_long_descriptive_name_padding = .col_0075_a_long_descriptive_name_padding,
    .col_0076_a_long_descriptive_name_padding = .col_0076_a_long_descriptive_name_padding,
    .col_0077_a_long_descriptive_name_padding = .col_0077_a_long_descriptive_name_padding,
    .col_0078_a_long_descriptive_name_padding = .col_0078_a_long_descriptive_name_padding,
    .col_0079_a_long_descriptive_name_padding = .col_0079_a_long_descriptive_name_padding,
    .col_0080_a_long_descriptive_name_padding = .col_0080_a_long_descriptive_name_padding,
    .col_0081_a_long_descriptive_name_padding = .col_0081_a_long_descriptive_name_padding,
    .col_0082_a_long_descriptive_name_padding = .col_0082_a_long_descriptive_name_padding,
    .col_0083_a_long_descriptive_name_padding = .col_0083_a_long_descriptive_name_padding,
    .col_0084_a_long_descriptive_name_padding = .col_0084_a_long_descriptive_name_padding,
    .col_0085_a_long_descriptive_name_padding = .col_0085_a_long_descriptive_name_padding,
    .col_0086_a_long_descriptive_name_padding = .col_0086_a_long_descriptive_name_padding,
    .col_0087_a_long_descriptive_name_padding = .col_0087_a_long_descriptive_name_padding,
    .col_0088_a_long_descriptive_name_padding = .col_0088_a_long_descriptive_name_padding,
    .col_0089_a_long_descriptive_name_padding = .col_0089_a_long_descriptive_name_padding,
    .col_0090_a_long_descriptive_name_padding = .col_0090_a_long_descriptive_name_padding,
    .col_0091_a_long_descriptive_name_padding = .col_0091_a_long_descriptive_name_padding,
    .col_0092_a_long_descriptive_name_padding = .col_0092_a_long_descriptive_name_padding,
    .col_0093_a_long_descriptive_name_padding = .col_0093_a_long_descriptive_name_padding,
    .col_0094_a_long_descriptive_name_padding = .col_0094_a_long_descriptive_name_padding,
    .col_0095_a_long_descriptive_name_padding = .col_0095_a_long_descriptive_name_padding,
    .col_0096_a_long_descriptive_name_padding = .col_0096_a_long_descriptive_name_padding,
    .col_0097_a_long_descriptive_name_padding = .col_0097_a_long_descriptive_name_padding,
    .col_0098_a_long_descriptive_name_padding = .col_0098_a_long_descriptive_name_padding,
    .col_0099_a_long_descriptive_name_padding = .col_0099_a_long_descriptive_name_padding,
    .col_0100_a_long_descriptive_name_padding = .col_0100_a_long_descriptive_name_padding,
    .col_0101_a_long_descriptive_name_padding = .col_0101_a_long_descriptive_name_padding,
    .col_0102_a_long_descriptive_name_padding = .col_0102_a_long_descriptive_name_padding,
    .col_0103_a_long_descriptive_name_padding = .col_0103_a_long_descriptive_name_padding,
    .col_0104_a_long_descriptive_name_padding = .col_0104_a_long_descriptive_name_padding,
    .col_0105_a_long_descriptive_name_padding = .col_0105_a_long_descriptive_name_padding,
    .col_0106_a_long_descriptive_name_padding = .col_0106_a_long_descriptive_name_padding,
    .col_0107_a_long_descriptive_name_padding = .col_0107_a_long_descriptive_name_padding,
    .col_0108_a_long_descriptive_name_padding = .col_0108_a_long_descriptive_name_padding,
    .col_0109_a_long_descriptive_name_padding = .col_0109_a_long_descriptive_name_padding,
    .col_0110_a_long_descriptive_name_padding = .col_0110_a_long_descriptive_name_padding,
    .col_0111_a_long_descriptive_name_padding = .col_0111_a_long_descriptive_name_padding,
    .col_0112_a_long_descriptive_name_padding = .col_0112_a_long_descriptive_name_padding,
    .col_0113_a_long_descriptive_name_padding = .col_0113_a_long_descriptive_name_padding,
    .col_0114_a_long_descriptive_name_padding = .col_0114_a_long_descriptive_name_padding,
    .col_0115_a_long_descriptive_name_padding = .col_0115_a_long_descriptive_name_padding,
    .col_0116_a_long_descriptive_name_padding = .col_0116_a_long_descriptive_name_padding,
    .col_0117_a_long_descriptive_name_padding = .col_0117_a_long_descriptive_name_padding,
    .col_0118_a_long_descriptive_name_padding = .col_0118_a_long_descriptive_name_padding,
    .col_0119_a_long_descriptive_name_padding = .col_0119_a_long_descriptive_name_padding,
    .col_0120_a_long_descriptive_name_padding = .col_0120_a_long_descriptive_name_padding,
    .col_0121_a_long_descriptive_name_padding = .col_0121_a_long_descriptive_name_padding,
    .col_0122_a_long_descriptive_name_padding = .col_0122_a_long_descriptive_name_padding,
    .col_0123_a_long_descriptive_name_padding = .col_0123_a_long_descriptive_name_padding,
    .col_0124_a_long_descriptive_name_padding = .col_0124_a_long_descriptive_name_padding,
    .col_0125_a_long_descriptive_name_padding = .col_0125_a_long_descriptive_name_padding,
    .col_0126_a_long_descriptive_name_padding = .col_0126_a_long_descriptive_name_padding,
    .col_0127_a_long_descriptive_name_padding = .col_0127_a_long_descriptive_name_padding,
    .col_0128_a_long_descriptive_name_padding = .col_0128_a_long_descriptive_name_padding,
    .col_0129_a_long_descriptive_name_padding = .col_0129_a_long_descriptive_name_padding,
    .col_0130_a_long_descriptive_name_padding = .col_0130_a_long_descriptive_name_padding,
    .col_0131_a_long_descriptive_name_padding = .col_0131_a_long_descriptive_name_padding,
    .col_0132_a_long_descriptive_name_padding = .col_0132_a_long_descriptive_name_padding,
    .col_0133_a_long_descriptive_name_padding = .col_0133_a_long_descriptive_name_padding,
    .col_0134_a_long_descriptive_name_padding = .col_0134_a_long_descriptive_name_padding,
    .col_0135_a_long_descriptive_name_padding = .col_0135_a_long_descriptive_name_padding,
    .col_0136_a_long_descriptive_name_padding = .col_0136_a_long_descriptive_name_padding,
    .col_0137_a_long_descriptive_name_padding = .col_0137_a_long_descriptive_name_padding,
    .col_0138_a_long_descriptive_name_padding = .col_0138_a_long_descriptive_name_padding,
    .col_0139_a_long_descriptive_name_padding = .col_0139_a_long_descriptive_name_padding,
    .col_0140_a_long_descriptive_name_padding = .col_0140_a_long_descriptive_name_padding,
    .col_0141_a_long_descriptive_name_padding = .col_0141_a_long_descriptive_name_padding,
    .col_0142_a_long_descriptive_name_padding = .col_0142_a_long_descriptive_name_padding,
    .col_0143_a_long_descriptive_name_padding = .col_0143_a_long_descriptive_name_padding,
    .col_0144_a_long_descriptive_name_padding = .col_0144_a_long_descriptive_name_padding,
    .col_0145_a_long_descriptive_name_padding = .col_0145_a_long_descriptive_name_padding,
    .col_0146_a_long_descriptive_name_padding = .col_0146_a_long_descriptive_name_padding,
    .col_0147_a_long_descriptive_name_padding = .col_0147_a_long_descriptive_name_padding,
    .col_0148_a_long_descriptive_name_padding = .col_0148_a_long_descriptive_name_padding,
    .col_0149_a_long_descriptive_name_padding = .col_0149_a_long_descriptive_name_padding,
    .col_0150_a_long_descriptive_name_padding = .col_0150_a_long_descriptive_name_padding,
    .col_0151_a_long_descriptive_name_padding = .col_0151_a_long_descriptive_name_padding,
    .col_0152_a_long_descriptive_name_padding = .col_0152_a_long_descriptive_name_padding,
    .col_0153_a_long_descriptive_name_padding = .col_0153_a_long_descriptive_name_padding,
    .col_0154_a_long_descriptive_name_padding = .col_0154_a_long_descriptive_name_padding,
    .col_0155_a_long_descriptive_name_padding = .col_0155_a_long_descriptive_name_padding,
    .col_0156_a_long_descriptive_name_padding = .col_0156_a_long_descriptive_name_padding,
    .col_0157_a_long_descriptive_name_padding = .col_0157_a_long_descriptive_name_padding,
    .col_0158_a_long_descriptive_name_padding = .col_0158_a_long_descriptive_name_padding,
    .col_0159_a_long_descriptive_name_padding = .col_0159_a_long_descriptive_name_padding,
    .col_0160_a_long_descriptive_name_padding = .col_0160_a_long_descriptive_name_padding,
    .col_0161_a_long_descriptive_name_padding = .col_0161_a_long_descriptive_name_padding,
    .col_0162_a_long_descriptive_name_padding = .col_0162_a_long_descriptive_name_padding,
    .col_0163_a_long_descriptive_name_padding = .col_0163_a_long_descriptive_name_padding,
    .col_0164_a_long_descriptive_name_padding = .col_0164_a_long_descriptive_name_padding,
    .col_0165_a_long_descriptive_name_padding = .col_0165_a_long_descriptive_name_padding,
    .col_0166_a_long_descriptive_name_padding = .col_0166_a_long_descriptive_name_padding,
    .col_0167_a_long_descriptive_name_padding = .col_0167_a_long_descriptive_name_padding,
    .col_0168_a_long_descriptive_name_padding = .col_0168_a_long_descriptive_name_padding,
    .col_0169_a_long_descriptive_name_padding = .col_0169_a_long_descriptive_name_padding,
    .col_0170_a_long_descriptive_name_padding = .col_0170_a_long_descriptive_name_padding,
    .col_0171_a_long_descriptive_name_padding = .col_0171_a_long_descriptive_name_padding,
    .col_0172_a_long_descriptive_name_padding = .col_0172_a_long_descriptive_name_padding,
    .col_0173_a_long_descriptive_name_padding = .col_0173_a_long_descriptive_name_padding,
    .col_0174_a_long_descriptive_name_padding = .col_0174_a_long_descriptive_name_padding,
    .col_0175_a_long_descriptive_name_padding = .col_0175_a_long_descriptive_name_padding,
    .col_0176_a_long_descriptive_name_padding = .col_0176_a_long_descriptive_name_padding,
    .col_0177_a_long_descriptive_name_padding = .col_0177_a_long_descriptive_name_padding,
    .col_0178_a_long_descriptive_name_padding = .col_0178_a_long_descriptive_name_padding,
    .col_0179_a_long_descriptive_name_padding = .col_0179_a_long_descriptive_name_padding,
    .col_0180_a_long_descriptive_name_padding = .col_0180_a_long_descriptive_name_padding,
    .col_0181_a_long_descriptive_name_padding = .col_0181_a_long_descriptive_name_padding,
    .col_0182_a_long_descriptive_name_padding = .col_0182_a_long_descriptive_name_padding,
    .col_0183_a_long_descriptive_name_padding = .col_0183_a_long_descriptive_name_padding,
    .col_0184_a_long_descriptive_name_padding = .col_0184_a_long_descriptive_name_padding,
    .col_0185_a_long_descriptive_name_padding = .col_0185_a_long_descriptive_name_padding,
    .col_0186_a_long_descriptive_name_padding = .col_0186_a_long_descriptive_name_padding,
    .col_0187_a_long_descriptive_name_padding = .col_0187_a_long_descriptive_name_padding,
    .col_0188_a_long_descriptive_name_padding = .col_0188_a_long_descriptive_name_padding,
    .col_0189_a_long_descriptive_name_padding = .col_0189_a_long_descriptive_name_padding,
    .col_0190_a_long_descriptive_name_padding = .col_0190_a_long_descriptive_name_padding,
    .col_0191_a_long_descriptive_name_padding = .col_0191_a_long_descriptive_name_padding,
    .col_0192_a_long_descriptive_name_padding = .col_0192_a_long_descriptive_name_padding,
    .col_0193_a_long_descriptive_name_padding = .col_0193_a_long_descriptive_name_padding,
    .col_0194_a_long_descriptive_name_padding = .col_0194_a_long_descriptive_name_padding,
    .col_0195_a_long_descriptive_name_padding = .col_0195_a_long_descriptive_name_padding,
    .col_0196_a_long_descriptive_name_padding = .col_0196_a_long_descriptive_name_padding,
    .col_0197_a_long_descriptive_name_padding = .col_0197_a_long_descriptive_name_padding,
    .col_0198_a_long_descriptive_name_padding = .col_0198_a_long_descriptive_name_padding,
    .col_0199_a_long_descriptive_name_padding = .col_0199_a_long_descriptive_name_padding,
};

test "a Row of 200 columns gets every statement without a quota of the caller's" {
    // Each call below is made with the compiler's default 1,000 branches
    // and nothing raised by the test.
    try testing.expect((comptime statement.select(Pg, Wide, @TypeOf(.{}))).sql.len > 0);
    try testing.expect((comptime statement.select(Lite, Wide, @TypeOf(.{ .where = .{ .id = 1 }, .order = .{ .id = .asc }, .limit = 5 }))).sql.len > 0);
    try testing.expect((comptime statement.find(Pg, Wide, i64)).sql.len > 0);
    try testing.expect((comptime statement.count(Pg, Wide, @TypeOf(.{}))).sql.len > 0);
    try testing.expect((comptime statement.page(Pg, Wide, @TypeOf(.{ .order = .{ .id = .asc }, .limit = 10 }))).sql.len > 0);
    try testing.expect((comptime statement.insert(Pg, Wide, @TypeOf(all_values))).sql.len > 0);
    try testing.expect((comptime statement.deleteReturning(Pg, Wide, @TypeOf(.{ .where = .{ .id = 1 } }))).sql.len > 0);
}

test "an update setting 200 columns is one statement, and so is its RETURNING" {
    const options = .{ .set = all_values, .where = .{ .id = 1 } };
    try testing.expect((comptime statement.update(Pg, Wide, @TypeOf(options))).sql.len > 0);
    try testing.expect((comptime statement.updateReturning(Pg, Wide, @TypeOf(options))).sql.len > 0);
}

test "a Row of 200 columns makes its table, its schema and its first migration" {
    try testing.expect((comptime ddl.createTable(Pg, Wide)).len > 0);
    try testing.expect((comptime ddl.createTable(Lite, Wide)).len > 0);
    try testing.expectEqual(@as(usize, 200), (comptime schema.expectationsOf(Pg, Wide)).len);
    const desired = comptime migrate.desiredOf(Pg, .{ .tables = &.{Wide} });
    var arena: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena.deinit();
    _ = try migrate.plan(arena.allocator(), Pg, desired, snapshot.empty(Pg));
}

test "a narrower Row of 200 columns borrows its table" {
    try testing.expectEqual(@as(usize, 200), (comptime row_mod.columnsOf(Narrow)).len);
    try testing.expect((comptime statement.select(Pg, Narrow, @TypeOf(.{}))).sql.len > 0);
    try testing.expect((comptime statement.find(Pg, Narrow, i64)).sql.len > 0);
}

test "an Ordering of 199 keys is read against a Row of 200 columns" {
    const Sort = ordering.Ordering(Wide, sort_keys);
    try testing.expect(Sort.most(Pg) > 0);
}

test "a typo in a Row of 200 columns is answered with the column nearest it" {
    const near = comptime row_mod.nearest(Wide, "col_0060_a_long_descriptive_name_paddinX");
    try testing.expectEqualStrings("col_0060_a_long_descriptive_name_padding", near.?);
}

test "a column of an enum of 600 values is a table, a check and a condition" {
    try testing.expect((comptime ddl.createTable(Pg, Labelled)).len > 0);
    try testing.expectEqual(@as(usize, 3), (comptime schema.expectationsOf(Pg, Labelled)).len);
    try testing.expect((comptime statement.select(Pg, Labelled, @TypeOf(.{ .where = .{ .kind = Kind.an_enum_value_with_a_longish_name_0005 } }))).sql.len > 0);
}

test "a raw statement listing 200 columns is checked against its Row" {
    comptime rawcheck.assertList(Pg, Wide, wide_select, "db.raw");
}

test "a Row with 24 aggregates, each with a .where, is one grouped statement" {
    const found = comptime shape.rows(Pg, Totals, @TypeOf(.{
        .where = .{ .agg_0001_a_long_aggregate_name_padding = .{ .gt = @as(i64, 0) } },
        .order = .{ .agg_0002_a_long_aggregate_name_padding = .desc },
    }), .many);
    try testing.expect(found.sql.len > 0);
    comptime shape.assertShape(Totals);
}
